tasks:
  - init: echo "Run 'bazel build //...' to build the project, 'bazel test //...' to run all tests.\n"
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-vscode.cpptools@0.27.0:z/UThvtoloHQ3y4wv5ptAw==
    - BazelBuild.vscode-bazel@0.3.0:e1QIKxacFdwGVP49DeXIaw==